package sales

// SaleStatus ...
type SaleStatus string

const (
	// SaleStatusAny  ...
	SaleStatusAny SaleStatus = "any"
	// SaleStatusNewLeads ...
	SaleStatusNewLeads SaleStatus = "new_leades"
	// SaleStatusPreSale ...
	SaleStatusPreSale SaleStatus = "pre_sale"
	// SaleStatusSale ...
	SaleStatusSale SaleStatus = "sale"
)

// JobStatus ...
type JobStatus string

const (
	// JobStatusNew ...
	JobStatusNew JobStatus = "new"
	// JobStatusPending ...
	JobStatusPending JobStatus = "pending"
	// JobStatusRejected ...
	JobStatusRejected JobStatus = "rejeted"
	// JobStatusSold ...
	JobStatusSold JobStatus = "sold"
)

// UserStatus ...
type UserStatus string

const (
	// UserStatusUnKnown ...
	UserStatusUnKnown UserStatus = "UNKNOWN"
	// UserStatusNotActivated ...
	UserStatusNotActivated UserStatus = "NOT_ACTIVATED"

	// UserStatusActivated ...
	UserStatusActivated UserStatus = "ACTIVATED"

	// UserStatusDeactivated ...
	UserStatusDeactivated UserStatus = "DEACTIVATED"
)
